name: bluetooth_low_energy_darwin
description: 'iOS and macOS implementation of the bluetooth_low_energy plugin.'
version: 7.0.0-dev.1
repository: https://github.com/yanshouwang/bluetooth_low_energy
issue_tracker: https://github.com/yanshouwang/bluetooth_low_energy/issues
topics:
  - bluetooth
  - bluetooth-low-energy
  - ble

environment:
  sdk: ^3.6.0
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: '>=3.7.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^7.0.0-dev.2
  logging: ^1.2.0
  hybrid_logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.7.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BluetoothLowEnergyDarwinPlugin
        sharedDarwinSource: true
        dartPluginClass: BluetoothLowEnergyDarwinPlugin
      macos:
        pluginClass: BluetoothLowEnergyDarwinPlugin
        sharedDarwinSource: true
        dartPluginClass: BluetoothLowEnergyDarwinPlugin
