name: bluetooth_low_energy_linux
description: "Linux implementation of the bluetooth_low_energy plugin."
version: 7.0.0-dev.5
repository: https://github.com/yanshouwang/bluetooth_low_energy
issue_tracker: https://github.com/yanshouwang/bluetooth_low_energy/issues
topics:
  - bluetooth
  - bluetooth-low-energy
  - ble

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^7.0.0-dev.5
  bluez: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: bluetooth_low_energy
    platforms:
      linux:
        pluginClass: BluetoothLowEnergyLinuxPlugin
        dartPluginClass: BluetoothLowEnergyLinuxPlugin
