name: bluetooth_low_energy_android
description: "Android implementation of the bluetooth_low_energy plugin."
version: 7.0.0-dev.5
repository: https://github.com/yanshouwang/bluetooth_low_energy
issue_tracker: https://github.com/yanshouwang/bluetooth_low_energy/issues
topics:
  - bluetooth
  - bluetooth-low-energy
  - ble

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy_platform_interface: ^7.0.0-dev.5
  logging: ^1.3.0
  hybrid_logging: ^1.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.1.0

flutter:
  plugin:
    implements: bluetooth_low_energy
    platforms:
      android:
        package: dev.hebei.bluetooth_low_energy_android
        pluginClass: BluetoothLowEnergyAndroidPlugin
        dartPluginClass: BluetoothLowEnergyAndroidPlugin
